// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudRecommenderV1
@_spi(GoogleCloudInternal) import GoogleCloudWkt

/// Log content of an action on a recommendation. This includes Mark* actions.
public struct ActionLog: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Required. User that executed this action. Eg, foo@gmail.com
  public var actor: Swift.String = Swift.String()

  /// Required. State change that was made by the actor. Eg, SUCCEEDED.
  public var state: GoogleCloudRecommenderV1.RecommendationStateInfo.State =
    GoogleCloudRecommenderV1.RecommendationStateInfo.State()

  /// Optional. Metadata that was included with the action that was taken.
  public var stateMetadata: [Swift.String: Swift.String] = [:]

  /// Required. Name of the recommendation which was acted on. Eg, :
  /// 'projects/123/locations/global/recommenders/roleReco/recommendations/r1'
  public var recommendationName: Swift.String = Swift.String()

  /// Initialize a new instance of `ActionLog`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ActionLog().with { $0.actor = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.recommender.logging.v1.ActionLog"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
